import{useEffect,useRef,useState}from'react';
import type{PointerEvent}from'react';
import{AlertTriangle,ArrowLeft,CheckCircle2,CircleHelp,FlaskConical,Link2,ShieldCheck,Trash2,Zap}from'lucide-react';
import{expectedResistors,idealResults,meterReading,parseQuantity,resistorPlacementsForMode,validateTopology}from'../lib/lab';
import type{LabMode,Meter,Placement}from'../lib/lab';
import{digitColors,experiments,stages}from'../data/lab';
import LabBoard from'./LabBoard';
import type{BoardDraft,BoardTool}from'./LabBoard';

type Saved={experimentId:number;variant:'parallel'|'series';placements:Placement[];meter:Meter;supplyVoltage:number;ratings:Record<string,string>;multisim:Record<string,string>;actual:Record<string,string>;explanations:Record<string,string>};
const initial:Saved={experimentId:4,variant:'parallel',placements:[],meter:{mode:'V',redPort:'VΩ',red:null,black:null},supplyVoltage:10,ratings:{'100':'2'},multisim:{},actual:{},explanations:{}};
function readSaved():Saved{try{return{...initial,...JSON.parse(localStorage.getItem('studylab.lab.v1')||'{}')}}catch{return initial}}
function format(n:number,unit=''){return`${unit==='mA'?n.toFixed(2):Number(n.toFixed(3))} ${unit}`}

function Schematic({mode,selectedNode,voltage,resistors,sourceKind,sourceLabel}:{mode:LabMode;selectedNode:string;voltage:number;resistors:number[];sourceKind:'V'|'I';sourceLabel:string}){
 const parallel=mode.endsWith('parallel'),centers=resistors.length===3?[107,160,213]:resistors.length===2?[125,195]:[155];
 const node=(x:number,y:number,id:string)=><g key={id}><circle cx={x} cy={y} r={selectedNode===id?10:6} fill={selectedNode===id?'#f0ab46':'#128d79'} stroke="#fff" strokeWidth="2"/><text x={x+16} y={y-8} className="lab-node-label">{id}</text></g>;
 const resistor=(x:number,y:number,r:number,i:number,series=false)=><g key={i}><rect x={x-14} y={y-22} width="28" height="44" rx="4" className="lab-resistor"/><text x={series?x-28:x} y={series?y+5:y-31} className={series?'lab-branch-value':'lab-value'}>R{i+1} · {format(r,'Ω')}</text></g>;
 const branchX=resistors.length===1?[375]:resistors.length===2?[285,455]:[255,370,485];
 let seriesWire=`M 470 70 V ${centers[0]-22} `;for(let i=0;i<centers.length-1;i++)seriesWire+=`M 470 ${centers[i]+22} V ${centers[i+1]-22} `;seriesWire+=`M 470 ${centers.at(-1)!+22} V 250`;
 return <svg viewBox="0 0 620 310" role="img" aria-label={`${parallel?'Parallel':'Series'} circuit with ${sourceKind==='V'?'voltage':'current'} source and ${resistors.length} resistors`} className="lab-schematic" direction="ltr">
  <rect width="620" height="310" rx="13" fill="#f4faf7"/>
  <path d={`M 105 70 H ${parallel?Math.max(...branchX):470} M 105 250 H ${parallel?Math.max(...branchX):470} M 105 70 V 126 M 105 184 V 250`} className="wire"/>
  <circle cx="105" cy="155" r="29" className="lab-source"/>{sourceKind==='V'?<><text x="105" y="149" className="lab-value">+</text><text x="105" y="171" className="lab-value">−</text></>:<path d="M 105 171 V 139 M 98 146 L 105 139 L 112 146" className="current-arrow"/>}<text x="105" y="211" className="lab-source-value">{sourceLabel||format(voltage,'V')}</text>
  {parallel?resistors.map((r,i)=>{const x=branchX[i];return <g key={i}><path d={`M ${x} 70 V 133 M ${x} 177 V 250`} className="wire"/>{resistor(x,155,r,i)}</g>}):<g><path d={seriesWire} className="wire"/>{resistors.map((r,i)=>resistor(470,centers[i],r,i,true))}{resistors.length===2&&node(470,160,'M')}{resistors.length===3&&<>{node(470,134,'M1')}{node(470,187,'M2')}</>}</g>}
  {node(105,70,'H')}{node(105,250,'L')}
  <text x="315" y="290" className="lab-caption">{parallel?'Parallel branches share the same voltage':'Series branches share the same current'}</text>
 </svg>
}

export default function Lab(){
 const[saved,setSaved]=useState<Saved>(readSaved);const[tool,setTool]=useState<BoardTool>('select');const[pending,setPending]=useState<string|null>(null);const[draft,setDraft]=useState<BoardDraft|null>(null);const[selected,setSelected]=useState<string|null>(null);const[message,setMessage]=useState('Choose a component, drag it onto the board, then connect two socket groups. Connect the source last.');const[powerOn,setPowerOn]=useState(false);const[supervisor,setSupervisor]=useState(false);const[metric,setMetric]=useState('I_total');const[color1,setColor1]=useState(1);const[color2,setColor2]=useState(0);const[multiplier,setMultiplier]=useState(1);const[tolerance,setTolerance]=useState(5);
 const[componentInputs,setComponentInputs]=useState({R:{amount:'220',unit:'Ω'},V:{amount:'10',unit:'V'},I:{amount:'75',unit:'mA'}});const[ratingInput,setRatingInput]=useState('2');
 const palettePointer=useRef<{x:number;y:number}|null>(null);
 const exp=experiments.find(e=>e.id===saved.experimentId)!;const mode:LabMode=saved.experimentId===4?`exp4-${saved.variant}`:saved.experimentId===5?`exp5-${saved.variant}`:saved.experimentId===2?'exp2':'exp3';
 const referenceRs=expectedResistors(mode),sourcePlacement=saved.placements.find(p=>p.kind==='V'||p.kind==='I');const source=!!sourcePlacement;
 const bridge: [string,string]|undefined=saved.meter.mode==='A'&&saved.meter.redPort!=='VΩ'&&saved.meter.red&&saved.meter.black?[saved.meter.red,saved.meter.black]:undefined;
 const topology=validateTopology(saved.placements,mode,bridge),baseTopology=validateTopology(saved.placements,mode);
 const placedRs=saved.placements.filter(p=>p.kind==='R');const orderedRs=placedRs.length===referenceRs.length?(baseTopology.valid?resistorPlacementsForMode(saved.placements,mode,baseTopology.nodeMap):placedRs):[];
 const Rs=orderedRs.length===referenceRs.length?orderedRs.map((p,i)=>p?.value||referenceRs[i]):referenceRs;
 const equivalentAtOneVolt=idealResults(mode,1,Rs).equivalent;
 const activeVoltage=sourcePlacement?.kind==='V'?sourcePlacement.value||0:sourcePlacement?.kind==='I'?(sourcePlacement.value||0)*equivalentAtOneVolt:saved.supplyVoltage;
 const ideal=idealResults(mode,activeVoltage,Rs);
 const selectedNode=selected?(topology.nodeMap[selected]||baseTopology.nodeMap[selected]||''):'';
 const meterResult=meterReading(saved.placements,mode,saved.meter,powerOn,activeVoltage);
 const expectedPower=Rs.map((r,i)=>({id:orderedRs[i]?.id||`reference-${i}`,r,power:ideal.currents[i]**2*r,rating:Number(saved.ratings[orderedRs[i]?.id||'']||orderedRs[i]?.rating||saved.ratings[String(r)]||0)}));
 const powerUnsafe=expectedPower.some(row=>row.rating>0&&row.power>row.rating+1e-9);const ratingsKnown=expectedPower.every(row=>row.rating>0);
 const canPower=source&&topology.valid&&!powerUnsafe&&ratingsKnown&&supervisor;
 const metrics=(()=>{
   const rows=[{key:'I_total',label:'التيار الكلي',value:ideal.totalCurrent*1000,unit:'mA'},{key:'V_source',label:'جهد المصدر',value:activeVoltage,unit:'V'},{key:'R_eq',label:'المقاومة المكافئة',value:ideal.equivalent,unit:'Ω'}];
   Rs.forEach((r,i)=>{rows.push({key:`I_R${i+1}`,label:`تيار R${i+1} (${r} Ω)`,value:ideal.currents[i]*1000,unit:'mA'});rows.push({key:`V_R${i+1}`,label:`جهد R${i+1} (${r} Ω)`,value:ideal.drops[i],unit:'V'})});return rows;
 })();
 const currentMetric=metrics.find(m=>m.key===metric)||metrics[0],recordKey=`${mode}:${sourcePlacement?.kind||'V'}:${activeVoltage}:${Rs.join(',')}:${metric}`;
 const simulated=Number(saved.multisim[recordKey]),actual=Number(saved.actual[recordKey]);
 const simFilled=saved.multisim[recordKey]!==undefined&&saved.multisim[recordKey]!=='';const actualFilled=saved.actual[recordKey]!==undefined&&saved.actual[recordKey]!=='';
 const percent=simFilled&&actualFilled&&currentMetric.value!==0?Math.abs(actual-currentMetric.value)/Math.abs(currentMetric.value)*100:null;
 const stageDone=[true,topology.valid,simFilled,actualFilled,simFilled&&actualFilled,!!saved.explanations[mode]];
 useEffect(()=>{localStorage.setItem('studylab.lab.v1',JSON.stringify(saved))},[saved]);
 function changeExperiment(id:number){setSaved(prev=>({...prev,experimentId:id,variant:'parallel',placements:[],meter:{mode:'V',redPort:'VΩ',red:null,black:null},supplyVoltage:10}));setPowerOn(false);setSupervisor(false);setPending(null);setDraft(null);setSelected(null);setTool('select');setMetric('I_total');setMessage('Choose a component, drag it onto the board, and connect its terminals.')}
 function changeVariant(v:'parallel'|'series'){setSaved(prev=>({...prev,variant:v,placements:[],meter:{mode:'V',redPort:'VΩ',red:null,black:null}}));setPowerOn(false);setPending(null);setDraft(null);setSelected(null);setMetric('I_total');setMessage('The reference circuit changed. Build a new connection.')}
 function makeDraft(kind:'R'|'V'|'I',position:{x:number;y:number}):BoardDraft|null{const input=componentInputs[kind],enteredValue=Number(input.amount),value=parseQuantity(kind,enteredValue,input.unit);if(value===null){setMessage(`Enter a valid ${kind==='R'?'resistance':kind==='V'?'voltage':'current'} value and a matching SI unit.`);return null}return{kind,value,enteredValue,unit:input.unit.trim(),position,rating:kind==='R'?Number(ratingInput)||undefined:undefined}}
 function suggestedPosition(kind:'R'|'V'|'I'){const candidates=kind==='R'?[{x:.28,y:.34},{x:.72,y:.34},{x:.28,y:.57},{x:.72,y:.57}]:[{x:.52,y:.76},{x:.52,y:.18},{x:.5,y:.57}];const occupied=saved.placements.filter(p=>p.kind!=='wire').map(p=>p.position||{x:.5,y:.5});if(!occupied.length)return candidates[0];return [...candidates].sort((a,b)=>Math.min(...occupied.map(p=>Math.hypot(b.x-p.x,b.y-p.y)))-Math.min(...occupied.map(p=>Math.hypot(a.x-p.x,a.y-p.y))))[0]}
 function updateInput(kind:'R'|'V'|'I',field:'amount'|'unit',text:string){const next={...componentInputs[kind],[field]:text};setComponentInputs(prev=>({...prev,[kind]:next}));if(draft?.kind===kind){const amount=Number(next.amount),value=parseQuantity(kind,amount,next.unit);setDraft(prev=>prev&&prev.kind===kind?{...prev,enteredValue:amount,unit:next.unit,value:value??prev.value}:prev)}}
 function placeDraft(kind:'R'|'V'|'I',position:{x:number;y:number}){if(powerOn){setMessage('Disconnect power before moving or adding a component.');return}if(source&&kind==='R'){setMessage('Remove the source first; it must be the last connection.');return}if(source&&(kind==='V'||kind==='I')){setMessage('A source is already connected. Remove it before adding another.');return}const next=makeDraft(kind,position);if(!next)return;setTool(kind);setPending(null);setDraft(next);setMessage(`Dropped ${kind==='R'?'resistor':kind==='V'?'voltage source':'current source'} on the board. Click its first and second socket groups.`)}
 function onDropPayload(payload:string,position:{x:number;y:number}){let data:unknown;try{data=JSON.parse(payload)}catch{return}if(!data||typeof data!=='object')return;const item=data as{moveId?:string;draftMove?:boolean;kind?:string};if(item.draftMove){setDraft(prev=>prev?{...prev,position}:prev);setMessage('Component preview moved. Click its first and second socket groups.');return}if(item.moveId){if(powerOn){setMessage('Disconnect power before moving a component.');return}setSaved(prev=>({...prev,placements:prev.placements.map(p=>p.id===item.moveId?{...p,position}:p)}));setMessage('Component moved on the board; its electrical connections are unchanged.');return}if(item.kind==='R'||item.kind==='V'||item.kind==='I')placeDraft(item.kind,position)}
 function selectTool(next:BoardTool){if((next==='R'||next==='V'||next==='I')&&source){setMessage('Remove the source before adding another element; connect it last.');return}if((next==='R'||next==='V'||next==='I')&&powerOn){setMessage('Disconnect power before editing the board.');return}setTool(next);setPending(null);const preview=next==='R'||next==='V'||next==='I'?makeDraft(next,suggestedPosition(next)):null;setDraft(preview);if((next==='R'||next==='V'||next==='I')&&!preview)return;setMessage(next==='wire'?'Wire: click the first socket group, then the second.':preview?'Drag the preview to position it, then click its first and second socket groups.':'Click a socket group to explore or place a probe.')}
 function finishPaletteDrag(event:PointerEvent<HTMLButtonElement>,kind:'R'|'V'|'I'){const start=palettePointer.current;palettePointer.current=null;if(!start||Math.hypot(event.clientX-start.x,event.clientY-start.y)<8)return;const board=document.querySelector('.board-grid');const rect=board?.getBoundingClientRect();if(!rect||event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)return;placeDraft(kind,{x:Math.max(.07,Math.min(.93,(event.clientX-rect.left)/rect.width)),y:Math.max(.07,Math.min(.93,(event.clientY-rect.top)/rect.height))})}
 function onSocket(group:string){setSelected(group);if(tool==='select')return;
   if(tool==='red'||tool==='black'){if(saved.meter.mode==='A')setPowerOn(false);setSaved(prev=>({...prev,meter:{...prev.meter,[tool]:group}}));setMessage(`${tool==='red'?'Red':'Black'} probe placed at ${group}.`);return}
   if(powerOn){setMessage('Disconnect power before editing any connection.');return}
   if(tool==='wire'&&source){setMessage('Remove the source first; it must be the last connection.');return}
   if(tool==='R'&&source){setMessage('Remove the source first; it must be the last connection.');return}
   if((tool==='V'||tool==='I')&&source){setMessage('A source is already connected. Remove it before adding another.');return}
   let active=draft;if(tool!=='wire'&&!active){active=makeDraft(tool,suggestedPosition(tool));if(!active)return;setDraft(active)}
   if(pending===null){setPending(group);setMessage(tool==='wire'?`Wire starts at ${group}. Click its destination node.`:`First terminal at ${group}. Click a different group for the second terminal.`);return}
   if(pending===group){setMessage('Choose another group; both terminals cannot use the same internal node.');return}
   if(tool==='V'||tool==='I'){if(source){setMessage('A source is already connected.');return}if(saved.placements.filter(p=>p.kind==='R').length!==referenceRs.length){setMessage(`Place ${referenceRs.length} resistors and any wires before connecting the source last.`);return}}
   if(tool!=='wire'){active=makeDraft(tool,active?.position||{x:.5,y:.5});if(!active)return}
   const id=`${tool}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
   const next:Placement=tool==='wire'?{id,kind:'wire',a:pending,b:group}:{id,kind:active!.kind,a:pending,b:group,value:active!.value,enteredValue:active!.enteredValue,unit:active!.unit,position:active!.position,rating:active!.rating};
   setSaved(prev=>({...prev,placements:[...prev.placements,next]}));setMessage(tool==='wire'?`Wire now joins ${pending} and ${group}.`:`${tool==='R'?'Resistor':tool==='V'?'Voltage source':'Current source'} is visible and connected from ${pending} to ${group}.`);setPending(null);setDraft(null)
 }
 function remove(id:string){const item=saved.placements.find(p=>p.id===id);if(!item)return;if(powerOn){setMessage('Disconnect power first.');return}if(source&&item.kind!=='V'&&item.kind!=='I'){setMessage('Remove the source first, then edit the remaining branches.');return}setSaved(prev=>({...prev,placements:prev.placements.filter(p=>p.id!==id)}));if(item.kind==='V'||item.kind==='I')setPowerOn(false);setMessage('Component removed from the board.')}
 function example(){const a='B2',b='C2',c='D2',d='E2';let rows:Placement[];if(Rs.length===1)rows=[{id:'ex-r1',kind:'R',a,b,value:Rs[0]},{id:'ex-v',kind:'V',a,b,value:saved.supplyVoltage,enteredValue:saved.supplyVoltage,unit:'V',position:{x:.52,y:.73}}];else if(mode.endsWith('parallel'))rows=[{id:'ex-r1',kind:'R',a,b,value:Rs[0]},{id:'ex-r2',kind:'R',a:c,b:d,value:Rs[1]},{id:'ex-w1',kind:'wire',a,b:c},{id:'ex-w2',kind:'wire',a:b,b:d}];else if(Rs.length===2)rows=[{id:'ex-r1',kind:'R',a,b,value:Rs[0]},{id:'ex-r2',kind:'R',a:c,b:d,value:Rs[1]},{id:'ex-w1',kind:'wire',a:b,b:c}];else rows=[{id:'ex-r1',kind:'R',a,b,value:Rs[0]},{id:'ex-r2',kind:'R',a:c,b:d,value:Rs[1]},{id:'ex-r3',kind:'R',a:'B4',b:'C4',value:Rs[2]},{id:'ex-w1',kind:'wire',a:b,b:c},{id:'ex-w2',kind:'wire',a:d,b:'B4'}];
   if(Rs.length>1)rows.push({id:'ex-v',kind:'V',a,b:mode.endsWith('parallel')?b:Rs.length===2?d:'C4',value:saved.supplyVoltage,enteredValue:saved.supplyVoltage,unit:'V',position:{x:.52,y:.73}});
   rows=rows.map((p,i)=>p.kind==='wire'?p:{...p,position:p.position||{x:i%2===0?.3:.68,y:.34},unit:p.unit||(p.kind==='R'?'Ω':p.kind==='V'?'V':'A'),enteredValue:p.enteredValue??p.value,rating:p.kind==='R'?Number(saved.ratings[String(p.value)]||0)||undefined:p.rating});
   setSaved(prev=>({...prev,placements:rows,meter:{mode:'V',redPort:'VΩ',red:null,black:null}}));setPowerOn(false);setTool('select');setPending(null);setDraft(null);setMessage('Loaded an electrically connected example. Drag components to rearrange them or inspect the wires.')
 }
 function setMeter<K extends keyof Meter>(key:K,value:Meter[K]){setSaved(prev=>({...prev,meter:{...prev.meter,[key]:value}}));if(powerOn&&(key==='mode'||key==='redPort'))setPowerOn(false)}
 return <div className="content lab-content"><div className="lab-header"><div><span className="eyebrow">مدرب المعمل البصري · EE247</span><h1>من المخطط إلى القراءة</h1><p>انقر المقبس لترى العقدة، ثم ابنِ الدائرة وقارن التوقع مع Multisim والقياس الفعلي.</p></div><span className="lab-photo-note"><FlaskConical size={18}/> صُممت اللوحة وفق صورة المعمل ودليله</span></div>
   <div className="experiment-tabs">{experiments.map(e=><button key={e.id} className={saved.experimentId===e.id?'active':''} onClick={()=>changeExperiment(e.id)}>تجربة {e.id}<small>{e.title}</small></button>)}</div>
   <div className="lab-intro"><div><span className="eyebrow">تجربة {exp.id} · ص {exp.page} من دليل EE247</span><h2>{exp.title}</h2><p>{exp.goal}</p><div className="lab-parts">{exp.parts.map(part=><span key={part}>{part}</span>)}</div></div>{['127.0.0.1','localhost'].includes(window.location.hostname)&&<a href={`/source/lab#page=${exp.page}`} target="_blank" rel="noreferrer">افتح صفحة الدليل <ArrowLeft size={16}/></a>}</div>
   <div className="lab-stages">{stages.map((s,i)=><div key={s} className={stageDone[i]?'done':''}><span>{stageDone[i]?<CheckCircle2 size={15}/>:i+1}</span><small>{s}</small></div>)}</div>
   {(saved.experimentId===4||saved.experimentId===5)&&<div className="lab-variant"><span>نوع الدائرة:</span><button className={saved.variant==='parallel'?'active':''} onClick={()=>changeVariant('parallel')}>توازٍ · {saved.experimentId===4?'KCL':'مقسّم تيار'}</button><button className={saved.variant==='series'?'active':''} onClick={()=>changeVariant('series')}>توالٍ · {saved.experimentId===4?'KVL':'مقسّم جهد'}</button></div>}
   <div className="lab-three"><section className="panel schematic-panel"><div className="panel-head"><div><span className="panel-kicker">01 · المخطط الكهربائي</span><h3>What wiring is required?</h3></div><span className="verified"><ShieldCheck size={15}/> مخطط مرجعي</span></div><Schematic mode={mode} selectedNode={selectedNode} voltage={activeVoltage} resistors={Rs} sourceKind={sourcePlacement?.kind==='I'?'I':'V'} sourceLabel={sourcePlacement?.kind==='I'?`${sourcePlacement.enteredValue??sourcePlacement.value} ${sourcePlacement.unit||'A'}`:format(activeVoltage,'V')}/><div className="prediction"><h4>أتوقع وأحسب</h4><div className="prediction-grid"><div><small>التيار الكلي</small><strong dir="ltr">{format(ideal.totalCurrent*1000,'mA')}</strong></div><div><small>المقاومة المكافئة</small><strong dir="ltr">{format(ideal.equivalent,'Ω')}</strong></div>{Rs.map((r,i)=><div key={i}><small>R{i+1} = {r} Ω</small><strong dir="ltr">{format(ideal.currents[i]*1000,'mA')} · {format(ideal.drops[i],'V')}</strong></div>)}</div><p className="prediction-note">Predictions use the values placed on the board when its required resistors are present.</p></div>{saved.experimentId===4&&<div className="photo-observation">من صورتك: شاشة المزود تعرض نحو 10.00 V و0.075 A، وشاشة الملتيميتر نحو 44.9. هذه قراءات مرئية تقريبية؛ أدخل قراءاتك الدقيقة للمقارنة.</div>}<div className="lab-tip"><CircleHelp size={17}/>{exp.tip}</div></section>
    <section className="panel board-panel">
     <div className="panel-head"><div><span className="panel-kicker">02 · Build on the board</span><h3>Drag elements, connect nodes</h3></div><button className="tiny-action" onClick={example}>Load example</button></div>
     <div className="board-instructions"><span><b>1</b> Choose an element and enter its value.</span><span><b>2</b> Drag it onto the board, or click to place a movable preview.</span><span><b>3</b> Click the first socket group, then the second.</span></div>
     <div className="element-palette">{(['R','V','I'] as const).map(kind=><button type="button" key={kind} onClick={event=>{if(event.detail===0)selectTool(kind)}} onPointerDown={event=>{palettePointer.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);selectTool(kind)}} onPointerUp={event=>finishPaletteDrag(event,kind)} className={tool===kind?'active':''} aria-label={`Drag ${kind==='R'?'resistor':kind==='V'?'voltage source':'current source'} to board`}><span className="element-icon">{kind==='R'?'▭':kind==='V'?'+ −':'➜'}</span><strong>{kind==='R'?'Resistor':kind==='V'?'Voltage source':'Current source'}</strong><small dir="ltr">{componentInputs[kind].amount} {componentInputs[kind].unit}</small></button>)}</div>
     <div className="component-settings"><label>Value<input aria-label="Element value" dir="ltr" type="number" step="any" value={componentInputs[tool==='R'||tool==='V'||tool==='I'?tool:'R'].amount} onChange={event=>updateInput(tool==='R'||tool==='V'||tool==='I'?tool:'R','amount',event.target.value)}/></label><label>Unit<input aria-label="Element unit" dir="ltr" list="lab-element-units" value={componentInputs[tool==='R'||tool==='V'||tool==='I'?tool:'R'].unit} onChange={event=>updateInput(tool==='R'||tool==='V'||tool==='I'?tool:'R','unit',event.target.value)}/><datalist id="lab-element-units">{(tool==='V'?['V','mV','kV']:tool==='I'?['A','mA','µA']:['Ω','mΩ','kΩ','MΩ']).map(unit=><option value={unit} key={unit}/>)}</datalist></label>{(tool==='R'||tool==='select'||tool==='wire'||tool==='red'||tool==='black')&&<label>Power rating<input aria-label="Resistor power rating" dir="ltr" type="number" min="0" step="any" value={ratingInput} onChange={event=>{setRatingInput(event.target.value);setDraft(prev=>prev?.kind==='R'?{...prev,rating:Number(event.target.value)||undefined}:prev)}}/><span>W</span></label>}</div>
     <div className="wire-tools"><button className={tool==='wire'?'active':''} onClick={()=>selectTool('wire')}>Cable · click node 1 → node 2</button><button className={tool==='select'?'active':''} onClick={()=>selectTool('select')}>Explore nodes</button><button className={tool==='red'?'active':''} onClick={()=>selectTool('red')}>Red probe</button><button className={tool==='black'?'active':''} onClick={()=>selectTool('black')}>Black probe</button></div>
     <p className="board-polarity" dir="ltr">Voltage source: first node is +, second is −. Current source: arrow flows from the first node to the second. Resistors and cables are bidirectional.</p>
     <LabBoard selected={selected} placements={saved.placements} tool={tool} pending={pending} draft={draft} onSocket={onSocket} onDropPayload={onDropPayload} onCancelDraft={()=>{setDraft(null);setPending(null);setMessage('Unconnected component cancelled.')}}/>
     <div className="board-feedback"><Link2 size={16}/><span>{selected?`Group ${selected}: all nine sockets are highlighted${selectedNode?`; it corresponds to schematic node ${selectedNode}`:''}.`:'Click any socket to highlight its electrical node.'}</span></div>
     <div className={`topology-status ${topology.valid?'good':'warn'}`}>{topology.valid?<CheckCircle2 size={18}/>:<AlertTriangle size={18}/>}<span>{topology.reason}</span></div>
     <div className="placed-list">{saved.placements.map(p=><div key={p.id}><span dir="ltr">{p.kind==='wire'?'Cable':`${p.kind==='R'?'R':p.kind==='V'?'V source':'I source'} · ${p.enteredValue??p.value} ${p.unit||(p.kind==='R'?'Ω':p.kind==='V'?'V':'A')}`}: {p.a} → {p.b}</span><button aria-label={`Remove ${p.id}`} onClick={()=>remove(p.id)}><Trash2 size={15}/></button></div>)}</div>
    </section>
    <section className="panel instruments-panel"><div className="panel-head"><div><span className="panel-kicker">03 · Instruments and readings</span><h3>Check before measuring</h3></div><Zap size={20}/></div>
     <div className="supply-card"><div><small>{sourcePlacement?.kind==='I'?'Current source':'DC voltage source'}</small><strong>{powerOn?'ON':'OFF'}</strong></div>{sourcePlacement?.kind==='I'?<span dir="ltr">{sourcePlacement.enteredValue??sourcePlacement.value} {sourcePlacement.unit||'A'}<small>Computed terminal voltage: {format(activeVoltage,'V')}</small></span>:<label>Voltage<input aria-label="Source voltage" type="number" step="any" value={sourcePlacement?.kind==='V'?sourcePlacement.value:saved.supplyVoltage} onChange={event=>{const value=Number(event.target.value);setSaved(prev=>({...prev,supplyVoltage:value,placements:prev.placements.map(p=>p.kind==='V'?{...p,value,enteredValue:value,unit:'V'}:p)}));setPowerOn(false)}}/> V</label>}</div>
     <div className={`power-alert ${powerUnsafe?'danger':!ratingsKnown?'caution':'safe'}`}><AlertTriangle size={18}/><div><strong>Power check before connecting a real source</strong>{expectedPower.map(({id,r,power,rating})=><p key={id}>{format(r,'Ω')}: {format(power,'W')} / {rating?`${rating} W`:'rating missing'} {rating&&power>rating?'· rating exceeded!':''}</p>)}</div></div>
     <div className="rating-inputs">{expectedPower.map(row=><label key={row.id}>Rating R · {format(row.r,'Ω')}<input aria-label={`Power rating for ${format(row.r,'Ω')}`} type="number" min="0" step="any" value={saved.ratings[row.id]??(row.rating||'')} onChange={event=>setSaved(prev=>({...prev,ratings:{...prev.ratings,[row.id]:event.target.value}}))} placeholder="W"/> W</label>)}</div>
     <label className="supervisor"><input type="checkbox" checked={supervisor} onChange={event=>setSupervisor(event.target.checked)}/> Supervisor present; I will connect the source last and disconnect it first.</label>
     <button className={`power-button ${powerOn?'on':''}`} onClick={()=>{if(powerOn){setPowerOn(false);setMessage('Virtual supply disconnected.')}else if(canPower){setPowerOn(true);setMessage('Virtual supply on; the safety checks passed.')}else setMessage('Cannot switch on: check topology, resistor ratings, and supervisor acknowledgement.')}}>{powerOn?'Disconnect virtual supply':'Switch on virtually'}</button>
     <div className="meter-card"><div className="meter-display"><small>Digital multimeter</small><strong dir="ltr">{meterResult.ok&&meterResult.value!==undefined?format(meterResult.value,meterResult.unit):'— — —'}</strong></div><div className="meter-controls"><label>Mode<select value={saved.meter.mode} onChange={event=>setMeter('mode',event.target.value as Meter['mode'])}><option value="V">V · voltage</option><option value="A">A · current</option><option value="Ω">Ω · resistance</option></select></label><label>Red port<select value={saved.meter.redPort} onChange={event=>setMeter('redPort',event.target.value as Meter['redPort'])}><option value="VΩ">VΩ</option><option value="mA">mA</option><option value="10A">10A</option></select></label></div><div className="probe-positions"><span>Red: {saved.meter.red||'—'}</span><span>Black COM: {saved.meter.black||'—'}</span></div><p className={meterResult.ok?'meter-good':'meter-warning'}>{meterResult.message}</p></div>
    </section></div>
   {saved.experimentId===2&&<div className="panel color-panel"><div><span className="panel-kicker">تجربة 2 · ألوان المقاومة</span><h3>اقرأ أربعة أشرطة</h3></div><div className="color-fields"><label>الأول<select value={color1} onChange={e=>setColor1(Number(e.target.value))}>{digitColors.map(([name,num])=><option value={num} key={num}>{name}</option>)}</select></label><label>الثاني<select value={color2} onChange={e=>setColor2(Number(e.target.value))}>{digitColors.map(([name,num])=><option value={num} key={num}>{name}</option>)}</select></label><label>المضاعف 10^<select value={multiplier} onChange={e=>setMultiplier(Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>التفاوت<select value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}><option value={5}>ذهبي ±5%</option><option value={10}>فضي ±10%</option><option value={1}>بني ±1%</option></select></label><strong dir="ltr">{(color1*10+color2)*10**multiplier} Ω ±{tolerance}%</strong></div><div className="power-example">عند 20 V على 100 Ω / 2 W: P = V²/R = <strong>4 W</strong>؛ يتجاوز التصنيف بمقدار الضعف.</div></div>}
   <div className="panel comparison-panel"><div className="panel-head"><div><span className="panel-kicker">المراحل 3–6</span><h3>Multisim → القياس → المقارنة → التفسير</h3></div><span className="manual-badge">إدخال يدوي</span></div><div className="comparison-grid"><label>الكمية<select value={metric} onChange={e=>setMetric(e.target.value)}>{metrics.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><div className="reference-value"><small>التوقع المحسوب</small><strong dir="ltr">{format(currentMetric.value,currentMetric.unit)}</strong></div><label>قراءة Multisim<input dir="ltr" type="number" step="any" value={saved.multisim[recordKey]||''} onChange={e=>setSaved(prev=>({...prev,multisim:{...prev.multisim,[recordKey]:e.target.value}}))} placeholder={currentMetric.unit}/></label><label>القراءة الفعلية<input dir="ltr" type="number" step="any" value={saved.actual[recordKey]||''} onChange={e=>setSaved(prev=>({...prev,actual:{...prev.actual,[recordKey]:e.target.value}}))} placeholder={currentMetric.unit}/></label></div><div className="comparison-result">{percent===null?'أدخل قراءتي Multisim والمعمل لإظهار الفرق.':`الفرق بين الفعلي والمثالي: ${format(percent,'%')}. فرق Multisim عن المثالي: ${format(Math.abs(simulated-currentMetric.value)/Math.abs(currentMetric.value)*100,'%')}.`}</div><label className="explanation">فسّر الفرق<textarea value={saved.explanations[mode]||''} onChange={e=>setSaved(prev=>({...prev,explanations:{...prev.explanations,[mode]:e.target.value}}))} placeholder="مثال: تفاوت المقاومة، دقة الجهاز، ومقاومة التلامس…" rows={3}/></label></div>
   <div className="lab-safety"><ShieldCheck size={20}/><span>تذكير المعمل: التغذية آخر توصيل وأول فصل، والتشغيل بوجود المشرف. قراءة Multisim والقياس الفعلي تُدخلان يدويًا.</span></div><div className="lab-message" role="status">{message}</div>
 </div>
}
