import{useEffect,useMemo,useState}from'react';
import{Activity,ArrowLeft,BookOpen,CheckCircle2,ChevronLeft,CircleHelp,ClipboardCheck,Clock3,Download,FlaskConical,GraduationCap,Lightbulb,RotateCcw,ShieldCheck,Target,Upload,XCircle}from'lucide-react';
import katex from'katex';
import rawProblems from'./data/circuits.json';
import{diagnostic,errorLabels}from'./data/diagnostic';
import Circuit from'./components/Circuit';
import Lab from'./components/Lab';
import CourseLibrary from'./components/CourseLibrary';
import Quiz2 from'./components/Quiz2';
import{useInterfaceLanguage}from'./i18n';
import type{ErrorType,Problem,Progress}from'./types';

const problems=rawProblems as unknown as Problem[];
const localSource=typeof window!=='undefined'&&['127.0.0.1','localhost'].includes(window.location.hostname);
const empty:Progress={diagnostic:{},errors:{nodes:0,direction:0,kcl_kvl:0,supernode:0,supermesh:0,dependent:0,algebra:0,units:0},attempts:{},mode:'learn'};
function readProgress():Progress{try{return {...empty,...JSON.parse(localStorage.getItem('studylab.progress.v1')||'{}')}}catch{return empty}}
function MathLine({tex}:{tex:string}){return <span className="math" dir="ltr" dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{throwOnError:false,displayMode:false})}}/>}
function VerificationDetails({problem}:{problem:Problem}){const format=(n:number)=>String(Number(n.toFixed(4)));return <><div className="verified-values">{Object.entries(problem.verified.nodes).map(([name,v])=><span key={name} dir="ltr">{name} = {format(v)} V</span>)}{Object.entries(problem.verified.meshCurrents||{}).map(([name,v])=><span key={name} dir="ltr">{name} = {format(v)} A</span>)}</div><details className="power-details"><summary>فحص القدرة وإعادة التعويض</summary><div>{Object.entries(problem.verified.powers||{}).map(([name,v])=><span key={name} dir="ltr">P({name}) = {format(v)} W</span>)}</div><strong>المجموع الجبري = {format(problem.verified.powerResidual)} W</strong></details></>}
function topicLabel(topic:string){return({nodal:'تحليل العقد',dependent:'مصدر تابع',supernode:'العقدة الفائقة',mesh:'تحليل المشّات',supermesh:'المشّ الفائق',choice:'اختيار الطريقة',error:'كشف الخطأ'} as Record<string,string>)[topic]||topic}
function classify(p:Problem){return p.error?.type|| (p.topic==='supernode'?'supernode':p.topic==='supermesh'?'supermesh':p.topic==='dependent'?'dependent':'kcl_kvl')}
function recommended(progress:Progress){const ranked=(Object.entries(progress.errors) as [ErrorType,number][]).sort((a,b)=>b[1]-a[1]);const main=ranked[0];const matching=main&&main[1]>0?problems.filter(p=>classify(p)===main[0]||(['nodes','direction','algebra','units'].includes(main[0])&&p.id!==progress.lastProblem)):[];return(matching.find(p=>p.id!==progress.lastProblem)||problems.find(p=>!progress.attempts[p.id])||problems[0]).id}
function ErrorPractice({problem,mode,lang,onFinish,onError,onNext}:{problem:Problem;mode:'learn'|'exam';lang:'en'|'ar';onFinish:(ok:boolean)=>void;onError:(type:ErrorType)=>void;onNext:()=>void}){
 const[answer,setAnswer]=useState(''),[done,setDone]=useState(false),[hint,setHint]=useState(0),[correct,setCorrect]=useState(false);
 const error=problem.error!;
 function submit(){if(!answer.trim())return;const normalize=(s:string)=>s.toLowerCase().replace(/[\s−–_{}]/g,c=>c==='−'||c==='–'?'-':'').replace(/\+0\.5/,'0.5');const ok=normalize(answer).includes(normalize(error.expected||''));setCorrect(ok);setDone(true);onFinish(ok);if(!ok)onError(error.type)}
 return <div className="panel work-panel"><div className="panel-head"><div><span className="panel-kicker">{lang==='ar'?'اكتشف الخطأ':'Find the error'}</span><h3>{lang==='ar'?'صحح الحل المكتوب':'Correct the written solution'}</h3></div><span className="step-pill">{mode==='learn'?'Learn':'Test'}</span></div><div className="step-body"><p dir="ltr">{error.question}</p><label>{lang==='ar'?'اكتب القيد الصحيح وفسّر الإشارة':'Write the corrected constraint and explain the sign'}<textarea dir="ltr" rows={5} value={answer} disabled={done} onChange={e=>setAnswer(e.target.value)} placeholder="For example: i2-i1=0.5 A because ..."/></label></div>{!done&&<div className="work-actions">{mode==='learn'&&<button className="hint-button" onClick={()=>setHint(h=>Math.min(3,h+1))}><Lightbulb size={17}/> {lang==='ar'?'تلميح':'Hint'} {hint?`${hint}/3`:''}</button>}<button className="primary" disabled={!answer.trim()} onClick={submit}>{lang==='ar'?'سلّم التفسير':'Submit explanation'} <ArrowLeft size={17}/></button></div>}{mode==='learn'&&hint>0&&!done&&<div className="hint-box"><span>{lang==='ar'?'مستوى التلميح':'Hint level'} {hint}</span><p>{lang==='ar'&&problem.hintsAr?problem.hintsAr[hint-1]:problem.hints[hint-1]}</p></div>}{done&&<><div className={`feedback ${correct?'good':'bad'}`}>{correct?'Constraint matched.':'Check the polarity or source arrow.'} {lang==='ar'&&error.explanationAr?error.explanationAr:error.explanation}</div><div className="solution"><div className="solution-head"><CheckCircle2 size={22}/><strong>{lang==='ar'?'الحل المتحقق منه':'Verified solution'}</strong></div><div className="equation-list">{(problem.meshEquations||problem.equations).map((eq,i)=><div key={i}><MathLine tex={eq}/></div>)}</div><VerificationDetails problem={problem}/><p>From the solved circuit: {problem.target.label} = <strong dir="ltr">{problem.verified.answerExact} {problem.target.unit}</strong>.</p><button className="text-action" onClick={onNext}>{lang==='ar'?'مسألة أخرى':'Another problem'} <ArrowLeft size={17}/></button></div></>}</div>
}
function App(){
 const[lang,setLang]=useInterfaceLanguage();
 const ui=(en:string,ar:string)=>lang==='en'?en:ar;
 const[progress,setProgress]=useState<Progress>(readProgress);const[screen,setScreen]=useState<'home'|'diagnostic'|'practice'|'lab'|'packs'|'quiz2'|'chapters'>(()=>Object.keys(readProgress().diagnostic).length===6?'home':'diagnostic');
 const[diagIndex,setDiagIndex]=useState(0);const[diagAnswer,setDiagAnswer]=useState('');const[diagDone,setDiagDone]=useState(false);
 const[problemId,setProblemId]=useState(()=>recommended(readProgress()));const[step,setStep]=useState(0);const[nodeCount,setNodeCount]=useState('');const[meshCount,setMeshCount]=useState('');const[method,setMethod]=useState<'nodal'|'mesh'|''>('');const[reason,setReason]=useState('');const[eqText,setEqText]=useState('');const[value,setValue]=useState('');const[unit,setUnit]=useState('');const[hintLevel,setHintLevel]=useState(0);const[feedback,setFeedback]=useState('');const[feedbackGood,setFeedbackGood]=useState(false);const[aiExplanation,setAiExplanation]=useState('');const[submitted,setSubmitted]=useState(false);const[busy,setBusy]=useState(false);const[activeNode,setActiveNode]=useState<string|null>(null);
 const problem=useMemo(()=>problems.find(p=>p.id===problemId)||problems[0],[problemId]);
 useEffect(()=>{localStorage.setItem('studylab.progress.v1',JSON.stringify(progress))},[progress]);
 function logError(type:ErrorType){setProgress(prev=>({...prev,errors:{...prev.errors,[type]:(prev.errors[type]||0)+1}}))}
 function resetProblem(id:string){setProblemId(id);setStep(0);setNodeCount('');setMeshCount('');setMethod('');setReason('');setEqText('');setValue('');setUnit('');setHintLevel(0);setFeedback('');setFeedbackGood(false);setAiExplanation('');setSubmitted(false);setScreen('practice')}
 function finish(correct:boolean){setSubmitted(true);setProgress(prev=>({...prev,lastProblem:problem.id,attempts:{...prev.attempts,[problem.id]:{correct,at:new Date().toISOString()}}}))}
 async function checkEquations(){try{const response=await fetch('/api/check-equations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:problem.id,equations:eqText})});return await response.json() as {ok:boolean;message:string}}catch{return{ok:false,message:'Equation-checking service is unavailable. Start the Python service.'}}}
 async function askAi(kind:'hint'|'error'){setAiExplanation('Rephrasing explanation…');try{const response=await fetch('/api/ai-explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:problem.id,kind,level:hintLevel||1,errorType:classify(problem),attempt:step===2?eqText:value,lang})});const result=await response.json() as {text:string;source:string};setAiExplanation(`${result.text} (${result.source==='model'?'optional model':'local course pack'})`)}catch{setAiExplanation('Explanation service is unavailable. The authored hints remain available.')}}
 async function validateStep(){setBusy(true);setFeedback('');let ok=false;let type:ErrorType='algebra';let message='';
   if(step===0){ok=Number(nodeCount)===problem.nodes.length&&Number(meshCount)===problem.verified.meshCount;type='nodes';message=ok?'صحيح: حدّدت العقد والمشّات.':`راجع السلك المتصل ثم العلاقة: عدد المشّات = الفروع − العقد + 1.`}
   else if(step===1){ok=method===problem.method&&reason.trim().length>=15;type=method!==problem.method?'kcl_kvl':classify(problem);message=ok?'اختيار مناسب لهذه الدائرة.':'عدّ المجهولات ولاحظ نوع المصدر ومكانه.'}
   else if(step===2){const result=await checkEquations();ok=result.ok;type=classify(problem);message=result.message}
   else {const numeric=Number(value);const target=problem.verified.answer;const unitOk=unit===problem.target.unit;ok=value.trim()!==''&&Number.isFinite(numeric)&&Math.abs(numeric-target)<=Math.max(.015,Math.abs(target)*.005)&&unitOk;type=unitOk?'algebra':'units';message=ok?'القيمة والإشارة والوحدة صحيحة.':!unitOk?'راجع الوحدة المطلوبة.':'راجع الجبر واتجاه الكمية؛ القيمة السالبة مقبولة إن كانت صحيحة.'}
   if(!ok)logError(type);
   setFeedback(message);setFeedbackGood(ok);setBusy(false);
   if(ok){if(step<3)setTimeout(()=>{setStep(s=>s+1);setFeedback('');setHintLevel(0)},450);else finish(true)}
 }
 async function submitExam(){setBusy(true);const eq=await checkEquations();const numberOk=value.trim()!==''&&Math.abs(Number(value)-problem.verified.answer)<=Math.max(.015,Math.abs(problem.verified.answer)*.005);const checks:[boolean,ErrorType][]=[
   [Number(nodeCount)===problem.nodes.length&&Number(meshCount)===problem.verified.meshCount,'nodes'],[method===problem.method&&reason.trim().length>=15,'kcl_kvl'],[eq.ok,classify(problem)],[numberOk,'algebra'],[unit===problem.target.unit,'units']];
   for(const [ok,type]of checks)if(!ok)logError(type);
   const count=checks.filter(c=>c[0]).length;setFeedback(`Your score: ${count} of ${checks.length}. ${eq.message}`);setFeedbackGood(count===checks.length);finish(count===checks.length);setBusy(false)
 }
 function submitDiagnostic(){if(!diagAnswer.trim())return;const task=diagnostic[diagIndex];const correct=task.check(diagAnswer);setProgress(prev=>({...prev,diagnostic:{...prev.diagnostic,[task.id]:correct},errors:correct?prev.errors:{...prev.errors,[task.type]:prev.errors[task.type]+1}}));setDiagDone(true)}
 async function importProgress(file:File|undefined){if(!file)return;try{const data=JSON.parse(await file.text());if(data.version!==1||!data.circuits||!data.circuits.errors||!data.circuits.attempts)throw Error('Progress file is not compatible.');localStorage.setItem('studylab.progress.v1',JSON.stringify(data.circuits));for(const [field,key] of [['lab','studylab.lab.v1'],['packs','studylab.packs.v1'],['packProgress','studylab.packProgress.v1'],['quiz2','studylab.quiz2.v2']] as const){if(data[field]===null||data[field]===undefined)localStorage.removeItem(key);else localStorage.setItem(key,JSON.stringify(data[field]))}window.location.reload()}catch(error){window.alert(error instanceof Error?error.message:'Unable to read progress file.')}}
 function nextDiagnostic(){if(diagIndex===5){setScreen('home');setProblemId(recommended(progress))}else{setDiagIndex(i=>i+1);setDiagAnswer('');setDiagDone(false)}}
 const doneCount=Object.keys(progress.attempts).length,diagScore=Object.values(progress.diagnostic).filter(Boolean).length;
 return <div className="app-shell">
   <aside className="sidebar"><div className="brand"><div className="brand-icon"><Activity size={27}/></div><div><strong>StudyLab</strong><small>مختبر التعلّم الذكي</small></div></div>
     <div className="side-group-label">مساحة العمل</div>
     <nav className="side-nav"><button className={screen==='home'?'selected':''} onClick={()=>setScreen('home')}><Target size={19}/> نظرة عامة</button><button className={screen==='diagnostic'?'selected':''} onClick={()=>setScreen('diagnostic')}><ClipboardCheck size={19}/> التشخيص السريع</button><button className={screen==='practice'?'selected':''} onClick={()=>setScreen('practice')}><BookOpen size={19}/> طاولة الحل</button><button className={screen==='quiz2'?'selected':''} onClick={()=>setScreen('quiz2')}><BookOpen size={19}/> Quiz 2</button><button className={screen==='chapters'?'selected':''} onClick={()=>setScreen('chapters')}><BookOpen size={19}/> تدريب الفصول</button><button className={screen==='lab'?'selected':''} onClick={()=>setScreen('lab')}><FlaskConical size={19}/> معمل EE247</button><button className={screen==='packs'?'selected':''} onClick={()=>setScreen('packs')}><GraduationCap size={19}/> حزم المقررات</button></nav>
     <div className="side-group-label">المقرر الحالي</div><div className="course-mini"><div className="course-mini-icon"><GraduationCap size={20}/></div><div><b>EE241 · الدوائر الكهربائية</b><small>الفصل 3: طرق التحليل</small></div></div>
     <div className="sidebar-bottom"><div className="streak-icon"><ShieldCheck size={21}/></div><div><strong>تقدّمك محفوظ محليًا</strong><small>يمكنك تصديره في أي وقت</small></div></div>
   </aside>
   <main className="main"><header className="topbar"><div className="crumb">StudyLab <ChevronLeft size={15}/> EE241 <ChevronLeft size={15}/> الفصل الثالث</div><div className="top-actions"><span className="status-dot"/> جاهز للمذاكرة <button className="language-toggle" onClick={()=>setLang(lang==='en'?'ar':'en')} aria-label={lang==='en'?'Switch interface to Arabic':'Switch interface to English'}>{lang==='en'?'العربية':'English'}</button><label title="استيراد التقدم" className="icon-btn progress-import"><Upload size={18}/><input type="file" accept=".json,application/json" onChange={e=>importProgress(e.target.files?.[0])}/></label><button title="تصدير التقدم" className="icon-btn" onClick={()=>{const saved=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};const report={version:1,exportedAt:new Date().toISOString(),circuits:progress,lab:saved('studylab.lab.v1'),packs:saved('studylab.packs.v1'),packProgress:saved('studylab.packProgress.v1'),quiz2:saved('studylab.quiz2.v2')};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='studylab-progress.json';a.click();URL.revokeObjectURL(a.href)}}><Download size={18}/></button></div></header>
     {screen==='home'&&<div className="content"><div className="hero"><div className="hero-text"><span className="eyebrow light">مسارك اليوم · EE241</span><h1>افهم الدائرة،<br/><em>ثم جرّب بنفسك.</em></h1><p>تدريب عملي على تحليل العقد والمشّات، مع تصحيح المعادلات وتتبع نوع الخطأ الذي يحتاج مراجعة.</p><div className="hero-actions"><button className="primary light-btn" onClick={()=>resetProblem(recommended(progress))}>ابدأ المسألة المقترحة <ArrowLeft size={18}/></button><button className="ghost-light" onClick={()=>setScreen('diagnostic')}>أعد التشخيص</button></div></div><div className="hero-graphic"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-node n1">a</div><div className="hero-node n2">b</div><div className="hero-node n3">g</div><div className="hero-line l1"/><div className="hero-line l2"/><div className="hero-line l3"/><div className="hero-resistor">R</div><div className="hero-formula">ΣI = 0</div></div></div>
       <div className="stat-grid"><div className="stat-card"><span className="stat-icon teal"><ClipboardCheck size={23}/></span><div><span>التشخيص</span><strong>{diagScore} / 6</strong><small>مهام صحيحة</small></div></div><div className="stat-card"><span className="stat-icon purple"><BookOpen size={23}/></span><div><span>المسائل المنجزة</span><strong>{doneCount} / {problems.length}</strong><small>من بنك الفصل</small></div></div><div className="stat-card"><span className="stat-icon orange"><RotateCcw size={23}/></span><div><span>أخطاء للمراجعة</span><strong>{Object.values(progress.errors).reduce((a,b)=>a+b,0)}</strong><small>توجّه الجلسة التالية</small></div></div></div>
       <div className="section-head"><div><span className="eyebrow">خطة التدريب</span><h2>اختر نقطة البداية</h2></div><span className="muted">مسائل أصلية متحقق منها بـ SymPy</span></div><div className="module-grid"><button className="module-card" onClick={()=>setScreen('diagnostic')}><span className="module-number">01</span><div className="module-icon green"><CircleHelp size={28}/></div><h3>اختبر الأساسيات</h3><p>ست مهام قصيرة تكشف مفهوم العقدة والاتجاه وKCL/KVL والقيود الخاصة.</p><span className="module-link">ابدأ التشخيص <ArrowLeft size={16}/></span></button><button className="module-card" onClick={()=>resetProblem(recommended(progress))}><span className="module-number">02</span><div className="module-icon violet"><BookOpen size={28}/></div><h3>تدرّب على الحل</h3><p>من الرسم إلى المعادلات والناتج، مع ثلاثة مستويات من التلميح.</p><span className="module-link">افتح طاولة الحل <ArrowLeft size={16}/></span></button><button className="module-card muted-card" onClick={()=>setScreen('lab')}><span className="module-number">03</span><div className="module-icon amber"><FlaskConical size={28}/></div><h3>ابنِ في المعمل</h3><p>لوحة التوصيل والقياسات لتجارب EE247 من 1 إلى 5.</p><span className="module-link">المرحلة التالية <ArrowLeft size={16}/></span></button></div>
       <div className="getting-started panel"><div><span className="eyebrow">{ui('Getting started','ابدأ من هنا')}</span><h2>{ui('How StudyLab works','طريقة استخدام StudyLab')}</h2></div><ol><li>{ui('Complete the six short-answer diagnostic tasks to locate gaps.','أجب عن مهام التشخيص الست لتعرف المفاهيم التي تحتاج مراجعة.')}</li><li>{ui('Open the Chapter 3 solve table: identify nodes and meshes, choose a method, enter equations, then submit a signed result with units.','افتح طاولة حل الفصل الثالث: حدّد العقد والمشّات، اختر الطريقة، اكتب المعادلات، ثم أدخل الناتج بإشارته ووحدته.')}</li><li>{ui('Use Learn for three hints; use Test to keep hints and solutions hidden until submission.','استخدم وضع التعلّم لثلاثة مستويات من التلميح، أو الاختبار لإخفائها حتى التسليم.')}</li><li>{ui('Quiz 2 covers only Chapter 3 through lecture PDF page 21 (slide 42). Chapters 4, 6, 7, and 8 are in Chapter practice.','كويز ٢ للفصل الثالث فقط حتى صفحة PDF رقم 21 (السلايد 42). تجد الفصول 4 و6 و7 و8 في تدريب الفصول.')}</li><li>{ui('In EE247, build the circuit, check the power rating, then record Multisim and physical readings. Export your progress from the top bar.','في EE247 ابنِ الدائرة، افحص تصنيف القدرة، ثم سجل قراءتي Multisim والمعمل. صدّر تقدمك من الشريط العلوي.')}</li></ol><div className="time-guide"><Clock3 size={17}/>{ui('Chapter 3 and Quiz 2: about 2 hours · Later chapter practice: about 12 hours.','الفصل الثالث وكويز ٢: نحو ساعتين · تدريب الفصول اللاحقة: نحو 12 ساعة.')}</div></div>
       <div className="quiz2-callout"><div><span className="eyebrow">EE241 · Quiz 2</span><h2>{ui('Chapter 3 written-response practice','تدريب الفصل الثالث المقالي')}</h2><p>{ui('Four original questions plus five adapted from cited Nilsson/Riedel problems, all within Chapter 3 lecture PDF pages 1–21.','أربع مسائل أصلية وخمس مقتبسة بتصرّف من تمارين Nilsson/Riedel الموثّقة، وكلها ضمن صفحات محاضرة الفصل الثالث 1–21.')}</p></div><button onClick={()=>setScreen('quiz2')}>{ui('Open Quiz 2','افتح Quiz 2')} <ArrowLeft size={17}/></button></div>
       <div className="review-strip"><div><span className="review-icon"><RotateCcw size={20}/></span><strong>Next review session</strong><p>{Object.values(progress.errors).some(Boolean)?`Start with a different problem on: ${errorLabels[(Object.entries(progress.errors).sort((a,b)=>b[1]-a[1])[0][0]) as ErrorType]}.`:'After your first attempt, a different problem will target the error type that appeared.'}</p></div><button onClick={()=>resetProblem(recommended(progress))}>Start now <ArrowLeft size={17}/></button></div>
       <div className="error-overview"><div className="section-head"><div><span className="eyebrow">سجلّ المحاولات</span><h2>الأخطاء حسب المفهوم</h2></div></div><div className="error-grid">{(Object.entries(errorLabels) as [ErrorType,string][]).map(([type,label])=><div key={type}><span>{label}</span><strong>{progress.errors[type]||0}</strong></div>)}</div></div>
     </div>}
     {screen==='diagnostic'&&<div className="content narrow"><div className="page-heading"><span className="eyebrow">{ui('Quick diagnostic · 6 tasks','تشخيص سريع · 6 مهام')}</span><h1>{ui('Check the basics before solving','راجع الأساسيات قبل الحل')}</h1><p>{ui('Write short answers in English. A wrong answer points to the concept to review.','اكتب إجابات قصيرة بالإنجليزية؛ عند الخطأ يظهر المفهوم الذي يحتاج مراجعة.')}</p></div><div className="progress-track"><div style={{width:`${((diagIndex+(diagDone?1:0))/6)*100}%`}}/></div><div className="diagnostic-card"><div className="question-top"><span>{ui('Task','المهمة')} {diagIndex+1} {ui('of','من')} 6</span><span>{diagnostic[diagIndex].title}</span></div><h2 dir="ltr">{diagnostic[diagIndex].question}</h2><label className="diagnostic-answer">{ui('Your answer','إجابتك')}<textarea dir="ltr" rows={4} value={diagAnswer} disabled={diagDone} onChange={e=>setDiagAnswer(e.target.value)} placeholder="Write a short answer and include units where relevant."/></label>{diagDone&&<div className={`feedback ${diagnostic[diagIndex].check(diagAnswer)?'good':'bad'}`}>{diagnostic[diagIndex].check(diagAnswer)?<CheckCircle2 size={20}/>:<XCircle size={20}/>}<span>{diagnostic[diagIndex].check(diagAnswer)?ui('Correct.','صحيح.'):diagnostic[diagIndex].review}<br/>{ui('Model answer:','الإجابة النموذجية:')} {diagnostic[diagIndex].sampleAnswer}</span></div>}<div className="card-actions"><button className="primary" disabled={!diagDone&&!diagAnswer.trim()} onClick={diagDone?nextDiagnostic:submitDiagnostic}>{diagDone?(diagIndex===5?ui('View study plan','اعرض الخطة'):ui('Next task','المهمة التالية')):ui('Check answer','تحقق من الإجابة')} <ArrowLeft size={17}/></button></div></div></div>}
     {screen==='practice'&&<div className="content practice-content"><div className="practice-header"><div><span className="eyebrow">طاولة الحل · {topicLabel(problem.topic)}</span><h1>{problem.title}</h1><p>Target quantity: <strong>{problem.target.label}</strong> using the drawn reference direction.</p></div><div className="mode-switch"><button className={progress.mode==='learn'?'active':''} onClick={()=>setProgress(p=>({...p,mode:'learn'}))}>تعلّم</button><button className={progress.mode==='exam'?'active':''} onClick={()=>setProgress(p=>({...p,mode:'exam'}))}>اختبار</button></div></div>
       <div className="practice-layout"><div className="problem-column"><div className="panel circuit-panel"><div className="panel-head"><div><span className="panel-kicker">الدائرة الكهربائية</span><h3>Read the diagram before writing equations</h3></div><span className="verified"><ShieldCheck size={15}/> متحقق منها</span></div><Circuit problem={problem} activeNode={activeNode}/><div className="circuit-meta"><span>العقد: {problem.nodes.filter(n=>n!=='g').map(n=><button key={n} className={activeNode===n?'active':''} onClick={()=>setActiveNode(activeNode===n?null:n)}>{n}</button>)} <button onClick={()=>setActiveNode(activeNode==='g'?null:'g')}>g</button></span><span>الأرضي: g = 0 V</span></div><div className="source-link">فكرة المهارة: {localSource?<a href={`/source/ch3#page=${problem.source.page}`} target="_blank" rel="noreferrer">EE241 Chapter 3 lecture, PDF p. {problem.source.page}</a>:<span>EE241 Chapter 3 lecture, PDF p. {problem.source.page}</span>} · {problem.source.origin}</div></div><div className="problem-list"><div className="panel-head"><h3>بنك المسائل</h3><span>{problems.length} مسائل</span></div><div className="problem-scroll">{problems.map((p,index)=><button key={p.id} onClick={()=>resetProblem(p.id)} className={p.id===problem.id?'active':''}><span className="problem-index">{String(index+1).padStart(2,'0')}</span><span><strong>{p.title}</strong><small>{topicLabel(p.topic)}</small></span>{progress.attempts[p.id]?.correct&&<CheckCircle2 size={16}/>}</button>)}</div></div></div>
         <div className="work-column">{problem.error?<ErrorPractice key={problem.id} problem={problem} mode={progress.mode} lang={lang} onFinish={finish} onError={logError} onNext={()=>resetProblem(recommended(progress))}/>:<><div className="steps"><div className={step>=0?'current':''}><span>1</span> العقد والمشّات</div><div className={step>=1?'current':''}><span>2</span> الطريقة والسبب</div><div className={step>=2?'current':''}><span>3</span> المعادلات</div><div className={step>=3?'current':''}><span>4</span> الناتج</div></div><div className="panel work-panel"><div className="panel-head"><div><span className="panel-kicker">الخطوة {step+1} من 4</span><h3>{['حدّد بنية الدائرة','اختر طريقة التحليل','اكتب المعادلات والقيود','أدخل الناتج والوحدة'][step]}</h3></div><span className="step-pill">{progress.mode==='learn'?'وضع التعلّم':'وضع الاختبار'}</span></div>
           {step===0&&<div className="step-body"><p>Count all electrical nodes, including ground, and the independent meshes. Explain your count in your working.</p><div className="two-fields"><label>عدد العقد<input inputMode="numeric" value={nodeCount} onChange={e=>setNodeCount(e.target.value)} placeholder="مثال: 3"/></label><label>عدد المشّات<input inputMode="numeric" value={meshCount} onChange={e=>setMeshCount(e.target.value)} placeholder="مثال: 2"/></label></div><div className="note">تذكير: السلك المتصل بلا عنصر لا ينشئ عقدة جديدة.</div></div>}
           {step===1&&<div className="step-body"><p>Which analysis method is simpler here? Select it and justify why.</p><div className="method-options"><button className={method==='nodal'?'chosen':''} onClick={()=>setMethod('nodal')}>تحليل العقد <small>KCL · جهود العقد</small></button><button className={method==='mesh'?'chosen':''} onClick={()=>setMethod('mesh')}>تحليل المشّات <small>KVL · تيارات المشّ</small></button></div><label className="select-label">Reason<textarea dir="ltr" rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the number of unknowns, the source type, or the special constraint."/></label></div>}
           {step===2&&<div className="step-body"><p>{problem.meshEquations?'Write KVL using clockwise mesh currents i1 and i2. Include a current-source constraint where needed.':'Write KCL using node voltages a, b, and c. Include voltage-source or dependent-source constraints where needed.'} Separate equations with <code>;</code>.</p><textarea dir="ltr" value={eqText} onChange={e=>setEqText(e.target.value)} placeholder={problem.meshEquations?'6*(i1-i2)=12; 6*(i2-i1)+2*i2+4*i2=0':'a/4 + (a-b)/2 = 3; b/6 + (b-a)/2 = -1'} rows={5}/><div className="note">اكتب الضرب بعلامة *، مثل 2*i1. يقبل التحقق ترتيبًا مختلفًا للحدود أو معادلات مكافئة.</div></div>}
           {step===3&&<div className="step-body"><p>Enter <strong>{problem.target.label}</strong> with the sign set by the indicated direction or polarity.</p><div className="answer-row"><label>القيمة<input dir="ltr" type="number" step="any" value={value} onChange={e=>setValue(e.target.value)} placeholder="0.00"/></label><label>الوحدة<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">اختر</option><option value="V">V</option><option value="A">A</option><option value="mA">mA</option><option value="Ω">Ω</option></select></label></div><div className="note">الإشارة السالبة تعني عكس الاتجاه المرجعي، وقد تكون صحيحة تمامًا.</div></div>}
           {feedback&&<div className={`feedback ${feedbackGood?'good':'bad'}`}>{feedback}{progress.mode==='learn'&&!submitted&&!feedbackGood&&<button className="explain-button" onClick={()=>askAi('error')}>اشرح الخطأ</button>}</div>}
           {!submitted&&<div className="work-actions">{progress.mode==='learn'&&<button className="hint-button" onClick={()=>setHintLevel(h=>Math.min(3,h+1))}><Lightbulb size={17}/> تلميح {hintLevel?`${hintLevel}/3`:''}</button>}<button className="primary" disabled={busy} onClick={progress.mode==='exam'?(step===3?submitExam:()=>{setStep(s=>s+1);setFeedback('')}):validateStep}>{busy?'أتحقق…':step===3?'سلّم المحاولة':'تحقق وتابع'} <ArrowLeft size={17}/></button></div>}
           {progress.mode==='learn'&&hintLevel>0&&!submitted&&<div className="hint-box"><span>تلميح المستوى {hintLevel}</span><p>{lang==='ar'&&problem.hintsAr?problem.hintsAr[hintLevel-1]:problem.hints[hintLevel-1]}</p><button className="explain-button" onClick={()=>askAi('hint')}>صياغة تلميح بديلة</button></div>}
           {aiExplanation&&progress.mode==='learn'&&!submitted&&<div className="ai-explanation">{aiExplanation}</div>}
           {submitted&&<div className="solution"><div className="solution-head"><CheckCircle2 size={22}/><strong>الحل المتحقق منه</strong></div><p>الطريقة المقترحة: {problem.method==='nodal'?'تحليل العقد':'تحليل المشّات'}. {lang==='ar'&&problem.reasonAr?problem.reasonAr:problem.reason}</p><div className="equation-list">{(problem.meshEquations||problem.equations).map((eq,i)=><div key={i}><MathLine tex={eq}/></div>)}{problem.matrix&&<div className="matrix-line"><MathLine tex={problem.matrix}/></div>}</div><VerificationDetails problem={problem}/><p>بإعادة التعويض: <strong dir="ltr">{problem.target.label} = {problem.verified.answerExact} {problem.target.unit}</strong>.</p><button className="text-action" onClick={()=>resetProblem(recommended(progress))}>مسألة أخرى لمعالجة أخطائي <ArrowLeft size={17}/></button></div>}
         </div></>}</div></div></div>}
     {screen==='quiz2'&&<Quiz2 key="quiz2" lang={lang} scope="quiz2"/>}
     {screen==='chapters'&&<Quiz2 key="chapters" lang={lang} scope="chapters"/>}
     {screen==='lab'&&<Lab/>}
     {screen==='packs'&&<CourseLibrary/>}
   <footer className="site-credit">{lang==='en'?'Prepared by Mohammed Al-Quraini, Electrical Engineering student.':'تم إعداده من الطالب محمد القريني، طالب الهندسة الكهربائية.'}</footer></main></div>
}
export default App;
